federation_version: 2
subgraphs:
  users:
    routing_url: "http://localhost:8002/"
    schema:
      subgraph_url: "http://localhost:8002/"
  profiles:
    routing_url: "http://localhost:8003/"
    schema:
      subgraph_url: "http://localhost:8003/"